@startuml kendaraan
actor Admin

usecase "Input Email dan Password" as UC10
usecase "Cek Kredensial" as UC11
usecase "Login Gagal" as UC12
usecase "Login Admin" as UC1
usecase "Akses Manajemen Data Kendaraan" as UC3
usecase "Tambah Kendaraan" as UC4
usecase "Edit Kendaraan" as UC5
usecase "Hapus Kendaraan" as UC6
usecase "Logout" as UC9

Admin --> UC10
UC10 --> UC11
UC11 --> UC12: tidak valid
UC12 --> UC10

UC11 --> UC1: valid
UC1 --> UC3
UC3 --> UC4: include
UC3 --> UC5: include
UC3 --> UC6: include
UC3 --> UC9 : extend

@enduml
