@startuml
start

:Login User;
if (Periksa Peran?) then (Admin)
    :Masuk ke Admin Panel;
else (User)
    :Pilih untuk membuat Thread;
    :Masukkan Judul dan Konten;
    :Simpan Thread ke Database;

    :Pilih Thread untuk Komentar;
    :Masukkan Komentar;
    :Simpan Komentar ke Database;

    :Pilih Thread untuk Voting;
    :Berikan Voting (Upvote/Downvote);
    :Simpan Voting ke Database;
endif

stop
@enduml